app:
  name: "LangChain Chatbot Sample"
  version: "0.1.0"
  environment: "development"

llm:
  provider: "openai"
  model: "gpt-4o-mini"
  temperature: 0.7
  max_tokens: 150

memory:
  type: "conversation_buffer"
  max_turns: 10
  k_context: 5

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/chatbot.log"

api:
  host: "0.0.0.0"
  port: 8000
  debug: true
